<?php

namespace SilverStripe\RecipePlugin;

use Composer\Command\BaseCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class InlineRecipeCommand extends BaseCommand
{
    public function configure()
    {
        $this->setName('inline');
        $this->setDescription('Invoke this command to inline a recipe into your root composer.json');
        $this->addArgument(
            'recipe',
            InputArgument::REQUIRED,
            'Recipe name to inline. Must be of type '
                . RecipePlugin::RECIPE
                . ' and be included in the root as a direct dependency'
        );
        $this->addUsage('composer inline silverstripe/recipe-blogging');
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
